### ISSUE TITLE
Rendering elements with class name "container" is generic and conflicts with libraries such as Bootstrap

### ISSUE THREAD

**Issue by bhalperin** [bimeister/pupakit#225]
The component _pupa-card_ (and maybe others too) markup includes generic classes such as `<div class="container">`. These generic class names conflict with popular libraries such as **Bootstrap**.
Recommend to prefix your class names with e.g. `pk-` for  distinguishing.

**Comment by vbabutskiy** [comment]
Thanks for your suggestion. We have added this task to the backlog.

**Comment by vbabutskiy** [comment]
Now all class names have prefix pupa-* https://github.com/bimeister/pupakit/pull/255
